openapi: 3.0.1
info:
  title: RX/SeaPort Consignment Info Rest Services
  description: These rest services provide information on consignments submitted to customs through Customs Cargo Messages (CUSCAR).
  contact:
    email: support@rxseaport.eu
  version: 1.0.0
externalDocs:
  description: Find out more about RX/SeaPort
  url: http://www.rxseaport.eu
servers:
- url: https://portal.rxseaport.eu/ords/prd/consignmentinfo/v1
paths:
  /bl/{blnumber}/stay/{stayreference}:
    get:
      tags:
      - "Consignment"
      summary: Consignment Details
      description: Provides consignment details for a passed-in stay reference and bill-of-lading.
      operationId: getConsignment
      parameters:
      - name: blnumber
        in: path
        description: Bill-of-lading number
        required: true
        schema:
          type: string
        example: 'TL01671083'
      - name: stayreference
        in: path
        description: Stay reference
        required: true
        schema:
          type: string
        example: '530864'
      - name: format
        in: query
        description: Response format
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            default: xml
            enum:
            - xml
            - json
      - name: token
        in: query
        description: Authentication token (aka API Key)
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsignmentDetail'
              #examples:
                #Example:
                  #$ref: '#/components/examples/200ConsignmentSearch'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConsignmentDetail'
        400:
          description: Bad Request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingParameter:
                  $ref: '#/components/examples/400MissingParameter'
                InvalidParameter:
                  $ref: '#/components/examples/400InvalidParameter'
                MissingData:
                  $ref: '#/components/examples/400MissingData'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingParameter:
                  $ref: '#/components/examples/400MissingParameter'
                InvalidParameter:
                  $ref: '#/components/examples/400InvalidParameter'
                MissingData:
                  $ref: '#/components/examples/400MissingData'
        403:
          description: Unauthorized
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingToken:
                  $ref: '#/components/examples/403MissingToken'
                InvalidToken:
                  $ref: '#/components/examples/403InvalidToken'
                DisabledToken:
                  $ref: '#/components/examples/403DisabledToken'
                ExpiredToken:
                  $ref: '#/components/examples/403ExpiredToken'
                UnauthorizedToken:
                  $ref: '#/components/examples/403UnauthorizedToken'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingToken:
                  $ref: '#/components/examples/403MissingToken'
                InvalidToken:
                  $ref: '#/components/examples/403InvalidToken'
                DisabledToken:
                  $ref: '#/components/examples/403DisabledToken'
                ExpiredToken:
                  $ref: '#/components/examples/403ExpiredToken'
                UnauthorizedToken:
                  $ref: '#/components/examples/403UnauthorizedToken'
        500:
          description: Application Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error:
                  $ref: '#/components/examples/500ApplicationError'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error:
                  $ref: '#/components/examples/500ApplicationError'
  /bl/{blnumber}:
    get:
      tags:
      - Consignment Search
      summary: Search Consignment
      description: Searches for a bill-of-lading number and returns all consignments containing the passed-in character set.
      operationId: searchConsignmentsByID
      parameters:
      - name: blnumber
        in: path
        description: Bill-of-lading search string
        required: true
        schema:
          type: string
        example: TL016710
      - name: format
        in: query
        description: Response format
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            default: xml
            enum:
            - xml
            - json
      - name: token
        in: query
        description: Authentication token (aka API Key)
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsignmentSearch'
              #examples:
                #Example:
                  #$ref: '#/components/examples/200ConsignmentSearch'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConsignmentSearch'
        400:
          description: Bad Request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingParameter:
                  $ref: '#/components/examples/400MissingParameter'
                InvalidParameter:
                  $ref: '#/components/examples/400InvalidParameter'
                MissingData:
                  $ref: '#/components/examples/400MissingData'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingParameter:
                  $ref: '#/components/examples/400MissingParameter'
                InvalidParameter:
                  $ref: '#/components/examples/400InvalidParameter'
                MissingData:
                  $ref: '#/components/examples/400MissingData'
        403:
          description: Unauthorized
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingToken:
                  $ref: '#/components/examples/403MissingToken'
                InvalidToken:
                  $ref: '#/components/examples/403InvalidToken'
                DisabledToken:
                  $ref: '#/components/examples/403DisabledToken'
                ExpiredToken:
                  $ref: '#/components/examples/403ExpiredToken'
                UnauthorizedToken:
                  $ref: '#/components/examples/403UnauthorizedToken'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingToken:
                  $ref: '#/components/examples/403MissingToken'
                InvalidToken:
                  $ref: '#/components/examples/403InvalidToken'
                DisabledToken:
                  $ref: '#/components/examples/403DisabledToken'
                ExpiredToken:
                  $ref: '#/components/examples/403ExpiredToken'
                UnauthorizedToken:
                  $ref: '#/components/examples/403UnauthorizedToken'
        500:
          description: Application Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error:
                  $ref: '#/components/examples/500ApplicationError'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error:
                  $ref: '#/components/examples/500ApplicationError'
  /stay/{stayreference}:
    get:
      tags:
      - "Consignment Search"
      summary: Stay Consignments
      description: Returns all consignments for a passed-in stay reference.
      operationId: searchConsignmentsByStay
      parameters:
      - name: stayreference
        in: path
        description: Stay Reference
        required: true
        schema:
          type: string
        example: 530864
      - name: format
        in: query
        description: Response format
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            default: xml
            enum:
            - xml
            - json
      - name: token
        in: query
        description: Authentication token (aka API Key)
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsignmentSearch'
              #examples:
                #Example:
                  #$ref: '#/components/examples/200ConsignmentSearch'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConsignmentSearch'
        400:
          description: Bad Request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingParameter:
                  $ref: '#/components/examples/400MissingParameter'
                InvalidParameter:
                  $ref: '#/components/examples/400InvalidParameter'
                MissingData:
                  $ref: '#/components/examples/400MissingData'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingParameter:
                  $ref: '#/components/examples/400MissingParameter'
                InvalidParameter:
                  $ref: '#/components/examples/400InvalidParameter'
                MissingData:
                  $ref: '#/components/examples/400MissingData'
        403:
          description: Unauthorized
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingToken:
                  $ref: '#/components/examples/403MissingToken'
                InvalidToken:
                  $ref: '#/components/examples/403InvalidToken'
                DisabledToken:
                  $ref: '#/components/examples/403DisabledToken'
                ExpiredToken:
                  $ref: '#/components/examples/403ExpiredToken'
                UnauthorizedToken:
                  $ref: '#/components/examples/403UnauthorizedToken'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MissingToken:
                  $ref: '#/components/examples/403MissingToken'
                InvalidToken:
                  $ref: '#/components/examples/403InvalidToken'
                DisabledToken:
                  $ref: '#/components/examples/403DisabledToken'
                ExpiredToken:
                  $ref: '#/components/examples/403ExpiredToken'
                UnauthorizedToken:
                  $ref: '#/components/examples/403UnauthorizedToken'
        500:
          description: Application Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error:
                  $ref: '#/components/examples/500ApplicationError'
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Error:
                  $ref: '#/components/examples/500ApplicationError'
components:
  schemas:
    ConsignmentSearch:
      type: object
      xml:
        namespace: 'http://www.rxseaport.eu/consignmentinfo'
        name: Consignments
      properties:
        "@VersionMajor":
          type: integer
          enum: [1]
          xml:
            attribute: true
            name: VersionMajor
        "@VersionMinor":
          type: integer
          enum: [0]
          xml:
            attribute: true
            name: VersionMinor
        Consignments:
          type: array
          xml:
            name: Consignment
          items:
            $ref: '#/components/schemas/ConsignmentSummary'
    ConsignmentSummary:
      type: object
      properties:
        BL:
          type: string
          example:
            'TL01670501'
        Stay:
          type: string
          example:
            '530864'
        Links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          example:
            - Link: { "href": 'https://portal.rxseaport.eu/ords/prd/consignmentinfo/v1/bl/TL01670501/stay/530864', "rel": "self" }
    ConsignmentDetail:
      type: object
      xml:
        namespace: 'http://www.rxseaport.eu/consignmentinfo'
        name: Consignment
      properties:
        "@VersionMajor":
          type: integer
          enum: [1]
          xml:
            attribute: true
            name: VersionMajor
        "@VersionMinor":
          type: integer
          enum: [0]
          xml:
            attribute: true
            name: VersionMinor
        BL:
          type: string
          example:
            'TL01670501'
        Manifest:
          type: object
          properties:
            Number:
              type: string
              example:
                '530864L9186182'
            Agent:
              type: string
              example:
                'P&O Ferries'
            Article:
              type: integer
              example:
                22
        Stay:
          type: object
          properties:
            Reference:
              type: string
              example:
                '530864'
            Vessel:
              $ref: '#/components/schemas/Vessel'
            Arrival:
              type: string
              format: date-time
              example:
                '2021-03-03T06:07:07Z'
            Origin:
              type: string
              example:
                Tilbury
            Destination:
              type: string
              example:
                Zeebrugge
            DischargeRTO:
              type: string
              example:
                'P&O Ferries (K107)'
            Links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              example:
                - Link: { "href": 'https://portal.rxseaport.eu/ords/prd/zedis/v1/stay/530864', "rel": "self" }
        Equipments:
          type: array
          items:
            $ref: '#/components/schemas/Equipment'
          example:
            - Equipment: { "EquipmentID": "TLLU1635614", "Qualifier": "Container", "SizeType": "20G0", "Status": "Non-Empty", "TransportCondition": "FCL", "Weight": 21000}
        Goods:
          type: array
          items:
            $ref: '#/components/schemas/Good'
          example:
            - Good: { "Sequence": 1, "Description": "PAPER REELS", "EquipmentID": "TLLU1635614", "Marks": "TLLU1635614/00101", "PackType": "Package", "PackCount": 40, "Weight": 12000, "CustomsStatus": "T1"}
            - Good: { "Sequence": 2, "Description": "PAPER REELS", "EquipmentID": "TLLU1635614", "Marks": "TLLU1635614/00201", "PackType": "Package", "PackCount": 30, "Weight": 9000, "CustomsStatus": "T1"}
    Vessel:
      type: object
      properties:
        IMO:
          type: string
          example:
            '9186182'
        Name:
          type: string
          example:
            'NORSKY'
        Links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          example:
            - Link: { "href": 'https://portal.rxseaport.eu/ords/prd/zedis/v1/vessel?imo=9186182', "rel": "self" }
    Equipment:
      type: object
      properties:
        Equipment:
          type: object
          properties:
            EquipmentID:
              type: string
              example:
                'TLLU1635614'
            Qualifier:
              type: string
              enum: [Container]
              example:
                'Container'
            SizeType:
              type: string
              example:
                '20G0'
            Status:
              type: string
              enum: [Empty, Non-Empty]
              example:
                'Non-Empty'
            TransportCondition:
              type: string
              enum: [FCL, LCL]
              example:
                'FCL'
            Weight:
              type: integer
              example:
                22903
    Good:
      type: object
      properties:
        Good:
          type: object
          properties:
            Sequence:
              type: integer
              example:
                1
            Description:
              type: string
              example:
                'PAPER REELS'
            EquipmentID:
              type: string
              example:
                'TLLU1635614'
            Marks:
              type: string
              example:
                'TLLU1635614/00101'
            PackType:
              type: string
              example:
                'Package'
            PackCount:
              type: integer
              example:
                40
            Weight:
              type: integer
              example:
                22903
            CustomsStatus:
              type: string
              example:
                'T1'
    Link:
      type: object
      properties:
        Link:
          type: object
          properties:
            href:
              type: string
              example:
                'https://portal.rxseaport.eu/ords/prd/consignmentinfo/v1/bl/TL01670501/stay/530864'
            rel:
              type: string
              example:
                'self'
    Error:
      type: object
      properties:
        Code:
          type: string
        Message:
          type: string
  examples:
    200ConsignmentSearch:
      summary: Example
      value: '{
                "VersionMajor": 1,
                "VersionMinor": 0,
                "Consignments": [
                  {
                    "BL": "TE02476239",
                    "Stay":"530648",
                    "Links": [
                      {
                        "href": "https://portal.rxseaport.eu/ords/prd/consignmentinfo/v1/bl/TE02476239/stay/530648",
                        "rel": "self"
                      }
                    ]
                  },
                  {
                    "BL": "TE02476242",
                    "Stay":"530648",
                    "Links": [
                      {
                        "href": "https://portal.rxseaport.eu/ords/prd/consignmentinfo/v1/bl/TE02476242/stay/530648",
                        "rel": "self"
                      }
                    ]
                  },
                  {
                    "BL": "TE02475693",
                    "Stay":"530648",
                    "Links": [
                      {
                        "href": "https://portal.rxseaport.eu/ords/prd/consignmentinfo/v1/bl/TE02475693/stay/530648",
                        "rel": "self"
                      }
                    ]
                  }
                ]
              }'
    400MissingData:
      summary: Missing Data
      value:
        Code: 'DATA_MISSING'
        Message: 'No data was found for your selection. Please try again with another selection.'
    400InvalidParameter:
      summary: Invalid Parameter
      value:
        Code: 'PARAMETER_INVALID'
        Message: 'The value for a passed-in parameter is invalid. Please consult the web service documentation.'
    400MissingParameter:
      summary: Missing Parameter
      value:
        Code: 'PARAMETER_MISSING'
        Message: 'A required input parameter is missing in your request. Please consult the web service documentation.'
    403DisabledToken:
      summary: Disabled Token
      value:
        Code: 'TOKEN_DISABLED'
        Message: 'The supplied token has been disabled. Please contact us for assistance.'
    403ExpiredToken:
      summary: Expired Token
      value:
        Code: 'TOKEN_EXPIRED'
        Message: 'The supplied token is expired. Please contact us for assistance.'
    403InvalidToken:
      summary: Invalid Token
      value:
        Code: 'TOKEN_INVALID'
        Message: 'An invalid access token was supplied. Double check that the token being passed in is valid or signup for a token.'
    403MissingToken:
      summary: Missing Token
      value:
        Code: 'TOKEN_MISSING'
        Message: 'An access token was not supplied. See documentation for details on how to pass your token to the web service.'
    403UnauthorizedToken:
      summary: Unauthorized Token
      value:
        Code: 'TOKEN_UNAUTHORIZED'
        Message: 'The supplied token is not authorized to access the given web service. Please contact us for assistance.'
    500ApplicationError:
      summary: Application Error
      value:
        Code: 'ORA-XXXXX'
        Message: 'Explanation for the error.'
